version: '3'
services:
  tracker:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_TOKEN
    links:
      - redis
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data: